### ISSUE TITLE
utf-8 + Chinese annotation in .py files make mistake

### ISSUE THREAD

**Issue by guaiu** [manchenkoff/source-code-calculator#1]
I have try several times. If my .py files use utf-8 coding and I write Chinese annotation in my files, your application will ignore these .py file. It is a pity......

**Comment by manchenkoff** [comment]
@guaiu Hi, could you give me an example of code or attach a file ignored in your case? I'll check it

**Comment by manchenkoff** [comment]
closed due inactivity
